### PR TITLE
Fixed replaces shown wrongly

### PR DESCRIPTION
**Pull request by AndersGM**

### CODE REVIEW

**Comment by r7kamura** [comment]
Thank you for your pull request! It looks generally good, so I'm going to merge it 😃 

I'm a little concerned about adding spaces. This may be fine for the kinds of languages that put spaces between words, but if not (For example, there are such things in some Asian languages), putting spaces in without permission may cause problems.

**Comment by r7kamura** [comment]
I noticed that TravisCI was no longer working, so I switched to GitHub Actions at #5. For that reason, I edited the gemspec a bit for the bundler version. I apologize for the inconvenience, but I hope you can resolve the conflicts.

It would be nice if you could address the spaces problem too, but I'm fine with it as is.

**Comment by AndersGM** [comment]
@r7kamura Thank you - I've remove the spaces in 62f8970d29a69fe6b12a32491776cc4b4027b081 :-)

**Comment by r7kamura** [comment]
Thank you so much! I've released a new version.

- https://rubygems.org/gems/markdiff/versions/0.7.0
- https://github.com/r7kamura/markdiff/releases/tag/v0.7.0

I haven't developed this library in a long time, so there may be some other problems. If you notice anything, please don't hesitate to submit a pull request 🙏

**Comment by AndersGM** [comment]
@r7kamura Haven't found other issues, but have a couple of ideas for improvements :-) Thank you for making the library open source!

**Pull request merged**
